server:
  port: 8081
spring:
  profiles:
    active: default
  application:
    name: fraud
  datasource:
    username: mohamedAli
    password: password
    url: jdbc:postgresql://localhost:5432/fraud

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
