spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8761

#because this is the eureka server itself we have to disable these to properties
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false